// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registration.Infrastructure.Data;

#nullable disable

namespace Registration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729163153_AddGradeMasterTables")]
    partial class AddGradeMasterTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LaneWayNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoBox")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RegistrationApi.Models.ApplicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PreferredSchool")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PreviousClassStudied")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousSchoolCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviousSchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("SiblingsInIndianSchools")
                        .HasColumnType("int");

                    b.Property<int>("SiblingsSeekingAdmission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("ApplicationDetails");
                });

            modelBuilder.Entity("RegistrationApi.Models.GradeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GradeDisplay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeCode = "LKG_HKG",
                            GradeDisplay = "LKG & HKG",
                            PreferenceType = "Multi-Choice Preference"
                        },
                        new
                        {
                            Id = 2,
                            GradeCode = "STD_1",
                            GradeDisplay = "Standard 1",
                            PreferenceType = "Regular Preference"
                        },
                        new
                        {
                            Id = 3,
                            GradeCode = "STD_9",
                            GradeDisplay = "Standard 9",
                            PreferenceType = "Regular Preference"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.GradeSchoolMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "SchoolName")
                        .IsUnique();

                    b.ToTable("GradeSchools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            SchoolName = "Indian School Muscat"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            SchoolName = "Indian School Darsait"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 2,
                            SchoolName = "Indian School Muscat"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.MotherTongueMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MotherTongues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.NationalityMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CivilId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("RegistrationApi.Models.PostalCodeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PostalCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Muscat-100",
                            Name = "Muscat"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeclarationAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNo")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("RegistrationApi.Models.RelationshipMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Father"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Mother"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "GrandFather"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "GrandMother"
                        });
                });

            modelBuilder.Entity("RegistrationApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherTongue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PassportExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VisaExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisaNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("RegistrationApi.Models.Address", b =>
                {
                    b.HasOne("RegistrationApi.Models.Registration", "Registration")
                        .WithOne("Address")
                        .HasForeignKey("RegistrationApi.Models.Address", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("RegistrationApi.Models.ApplicationDetail", b =>
                {
                    b.HasOne("RegistrationApi.Models.Registration", "Registration")
                        .WithOne("ApplicationDetail")
                        .HasForeignKey("RegistrationApi.Models.ApplicationDetail", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("RegistrationApi.Models.GradeSchoolMaster", b =>
                {
                    b.HasOne("RegistrationApi.Models.GradeMaster", "Grade")
                        .WithMany("Schools")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("RegistrationApi.Models.Parent", b =>
                {
                    b.HasOne("RegistrationApi.Models.Registration", "Registration")
                        .WithOne("Parent")
                        .HasForeignKey("RegistrationApi.Models.Parent", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("RegistrationApi.Models.Student", b =>
                {
                    b.HasOne("RegistrationApi.Models.Registration", "Registration")
                        .WithOne("Student")
                        .HasForeignKey("RegistrationApi.Models.Student", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("RegistrationApi.Models.GradeMaster", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("RegistrationApi.Models.Registration", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("ApplicationDetail");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}

