// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registration.Infrastructure.Data;

#nullable disable

namespace Registration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730055205_SeedPostalCodesData")]
    partial class SeedPostalCodesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Registration.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LaneWayNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoBox")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Registration.Domain.Entities.ApplicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PreferredSchool")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PreviousClassStudied")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousSchoolCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviousSchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("SiblingsInIndianSchools")
                        .HasColumnType("int");

                    b.Property<int>("SiblingsSeekingAdmission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("ApplicationDetails");
                });

            modelBuilder.Entity("Registration.Domain.Entities.GradeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("grade_code");

                    b.Property<string>("GradeDisplay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grade_display");

                    b.Property<int>("PreferenceCount")
                        .HasColumnType("int")
                        .HasColumnName("preference_count");

                    b.HasKey("Id");

                    b.HasIndex("GradeCode")
                        .IsUnique();

                    b.ToTable("master_grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeCode = "LKG_1",
                            GradeDisplay = "LKG 1",
                            PreferenceCount = 8
                        },
                        new
                        {
                            Id = 2,
                            GradeCode = "LKG_2",
                            GradeDisplay = "LKG 2",
                            PreferenceCount = 8
                        },
                        new
                        {
                            Id = 3,
                            GradeCode = "LKG_3",
                            GradeDisplay = "LKG 3",
                            PreferenceCount = 9
                        },
                        new
                        {
                            Id = 4,
                            GradeCode = "STD_I",
                            GradeDisplay = "Std I",
                            PreferenceCount = 11
                        },
                        new
                        {
                            Id = 5,
                            GradeCode = "STD_II",
                            GradeDisplay = "Std II",
                            PreferenceCount = 10
                        },
                        new
                        {
                            Id = 6,
                            GradeCode = "STD_III",
                            GradeDisplay = "Std III",
                            PreferenceCount = 8
                        },
                        new
                        {
                            Id = 7,
                            GradeCode = "STD_IV",
                            GradeDisplay = "Std IV",
                            PreferenceCount = 8
                        },
                        new
                        {
                            Id = 8,
                            GradeCode = "STD_V",
                            GradeDisplay = "Std V",
                            PreferenceCount = 7
                        },
                        new
                        {
                            Id = 9,
                            GradeCode = "STD_VI",
                            GradeDisplay = "Std VI",
                            PreferenceCount = 7
                        },
                        new
                        {
                            Id = 10,
                            GradeCode = "STD_VII",
                            GradeDisplay = "Std VII",
                            PreferenceCount = 7
                        },
                        new
                        {
                            Id = 11,
                            GradeCode = "STD_VIII",
                            GradeDisplay = "Std VIII",
                            PreferenceCount = 6
                        },
                        new
                        {
                            Id = 12,
                            GradeCode = "STD_IX",
                            GradeDisplay = "Std IX",
                            PreferenceCount = 5
                        },
                        new
                        {
                            Id = 13,
                            GradeCode = "STD_XI",
                            GradeDisplay = "Std XI",
                            PreferenceCount = 5
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.GradeSchoolMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("school_option_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("school_name");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "SchoolName")
                        .IsUnique()
                        .HasDatabaseName("unique_grade_school");

                    b.ToTable("grade_schools");
                });

            modelBuilder.Entity("Registration.Domain.Entities.MotherTongueMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MotherTongues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.NationalityMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CivilId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Registration.Domain.Entities.PostalCodeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PostalCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Muscat-100",
                            Name = "Muscat"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Bareeq Al Shatti-103",
                            Name = "Bareeq Al Shatti"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Markaz al Bahja-104",
                            Name = "Markaz al Bahja"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Central Post Office-111",
                            Name = "Central Post Office"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Ruwi-112",
                            Name = "Ruwi"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Muscat-113",
                            Name = "Muscat"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Jabroo-114",
                            Name = "Jabroo"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Madinat Al Sultan Qaboos-115",
                            Name = "Madinat Al Sultan Qaboos"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Mina Al Fahal-116",
                            Name = "Mina Al Fahal"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Al Wadi Al Kabir-117",
                            Name = "Al Wadi Al Kabir"
                        },
                        new
                        {
                            Id = 11,
                            Code = "Al Harthy Complex-118",
                            Name = "Al Harthy Complex"
                        },
                        new
                        {
                            Id = 12,
                            Code = "Al Amarat-119",
                            Name = "Al Amarat"
                        },
                        new
                        {
                            Id = 13,
                            Code = "Qurayat-120",
                            Name = "Qurayat"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Al Seeb-121",
                            Name = "Al Seeb"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Al-Maabela -122",
                            Name = "Al-Maabela "
                        },
                        new
                        {
                            Id = 16,
                            Code = "Sultan Qaboos University-123",
                            Name = "Sultan Qaboos University"
                        },
                        new
                        {
                            Id = 17,
                            Code = "Al Rusayl -124",
                            Name = "Al Rusayl "
                        },
                        new
                        {
                            Id = 18,
                            Code = "Muttrah-125",
                            Name = "Muttrah"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Oman Commercial Center-126",
                            Name = "Oman Commercial Center"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Khaula Hospital-127",
                            Name = "Khaula Hospital"
                        },
                        new
                        {
                            Id = 21,
                            Code = "Seeb Airport-128",
                            Name = "Seeb Airport"
                        },
                        new
                        {
                            Id = 22,
                            Code = "Al Murtafa-129",
                            Name = "Al Murtafa"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Azaiba-130",
                            Name = "Azaiba"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Al Hamriyah-131",
                            Name = "Al Hamriyah"
                        },
                        new
                        {
                            Id = 25,
                            Code = "Al Khud-132",
                            Name = "Al Khud"
                        },
                        new
                        {
                            Id = 26,
                            Code = "Al Khuwair-133",
                            Name = "Al Khuwair"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Jawharat Al Shati-134",
                            Name = "Jawharat Al Shati"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Central Salalah -211",
                            Name = "Central Salalah "
                        },
                        new
                        {
                            Id = 29,
                            Code = "Quirun Hairiti-212",
                            Name = "Quirun Hairiti"
                        },
                        new
                        {
                            Id = 30,
                            Code = "Teetam-213",
                            Name = "Teetam"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Al-Dahareez-214",
                            Name = "Al-Dahareez"
                        },
                        new
                        {
                            Id = 32,
                            Code = "Al-Hafa-216",
                            Name = "Al-Hafa"
                        },
                        new
                        {
                            Id = 33,
                            Code = "AlAwqadain-217",
                            Name = "AlAwqadain"
                        },
                        new
                        {
                            Id = 34,
                            Code = "Taqa-218",
                            Name = "Taqa"
                        },
                        new
                        {
                            Id = 35,
                            Code = "Madinat-Al - Haq-219",
                            Name = "Madinat-Al - Haq"
                        },
                        new
                        {
                            Id = 36,
                            Code = "Marbat-220",
                            Name = "Marbat"
                        },
                        new
                        {
                            Id = 37,
                            Code = "Tiwi Atair-221",
                            Name = "Tiwi Atair"
                        },
                        new
                        {
                            Id = 38,
                            Code = "Thamrait-222",
                            Name = "Thamrait"
                        },
                        new
                        {
                            Id = 39,
                            Code = "Sohar-311",
                            Name = "Sohar"
                        },
                        new
                        {
                            Id = 40,
                            Code = "Al Musana a -312",
                            Name = "Al Musana a "
                        },
                        new
                        {
                            Id = 41,
                            Code = "Widam-Al - Sahil-313",
                            Name = "Widam-Al - Sahil"
                        },
                        new
                        {
                            Id = 42,
                            Code = "Al-Malda -314",
                            Name = "Al-Malda "
                        },
                        new
                        {
                            Id = 43,
                            Code = "Al Suwaiq-315",
                            Name = "Al Suwaiq"
                        },
                        new
                        {
                            Id = 44,
                            Code = "Al Bidaya-316",
                            Name = "Al Bidaya"
                        },
                        new
                        {
                            Id = 45,
                            Code = "Al Awabi-317",
                            Name = "Al Awabi"
                        },
                        new
                        {
                            Id = 46,
                            Code = "Al Rustaq-318",
                            Name = "Al Rustaq"
                        },
                        new
                        {
                            Id = 47,
                            Code = "Saham-319",
                            Name = "Saham"
                        },
                        new
                        {
                            Id = 48,
                            Code = "Barka-320",
                            Name = "Barka"
                        },
                        new
                        {
                            Id = 49,
                            Code = "Al Tarif-321",
                            Name = "Al Tarif"
                        },
                        new
                        {
                            Id = 50,
                            Code = "Falaj-Al - Qabail-322",
                            Name = "Falaj-Al - Qabail"
                        },
                        new
                        {
                            Id = 51,
                            Code = "Nakhal-323",
                            Name = "Nakhal"
                        },
                        new
                        {
                            Id = 52,
                            Code = "Shinas-324",
                            Name = "Shinas"
                        },
                        new
                        {
                            Id = 53,
                            Code = "Liwa-325",
                            Name = "Liwa"
                        },
                        new
                        {
                            Id = 54,
                            Code = "Al Khaboura-326",
                            Name = "Al Khaboura"
                        },
                        new
                        {
                            Id = 55,
                            Code = "Sohar-Industrial-327",
                            Name = "Sohar-Industrial"
                        },
                        new
                        {
                            Id = 56,
                            Code = "Burj-Al - Radah-329",
                            Name = "Burj-Al - Radah"
                        },
                        new
                        {
                            Id = 57,
                            Code = "Sur-411",
                            Name = "Sur"
                        },
                        new
                        {
                            Id = 58,
                            Code = "Al-Kamil & Al-Wafi -412",
                            Name = "Al-Kamil & Al-Wafi "
                        },
                        new
                        {
                            Id = 59,
                            Code = "Ibra-413",
                            Name = "Ibra"
                        },
                        new
                        {
                            Id = 60,
                            Code = "Masirah-414",
                            Name = "Masirah"
                        },
                        new
                        {
                            Id = 61,
                            Code = "Ja alan Bani Bu Hassan-415",
                            Name = "Ja alan Bani Bu Hassan"
                        },
                        new
                        {
                            Id = 62,
                            Code = "Ja alan Bani Bu Ali -416",
                            Name = "Ja alan Bani Bu Ali "
                        },
                        new
                        {
                            Id = 63,
                            Code = "Wadi Bani Khalid -417",
                            Name = "Wadi Bani Khalid "
                        },
                        new
                        {
                            Id = 64,
                            Code = "Sinaw-418",
                            Name = "Sinaw"
                        },
                        new
                        {
                            Id = 65,
                            Code = "Al Mudhairib-419",
                            Name = "Al Mudhairib"
                        },
                        new
                        {
                            Id = 66,
                            Code = "Al Mudhaibi-420",
                            Name = "Al Mudhaibi"
                        },
                        new
                        {
                            Id = 67,
                            Code = "Bidiyah-421",
                            Name = "Bidiyah"
                        },
                        new
                        {
                            Id = 68,
                            Code = "Al-Ashkharah-422",
                            Name = "Al-Ashkharah"
                        },
                        new
                        {
                            Id = 69,
                            Code = "Samad-Al - Shan-423",
                            Name = "Samad-Al - Shan"
                        },
                        new
                        {
                            Id = 70,
                            Code = "Dama-Wattaeen-424",
                            Name = "Dama-Wattaeen"
                        },
                        new
                        {
                            Id = 71,
                            Code = "Sur Commercial District -425",
                            Name = "Sur Commercial District "
                        },
                        new
                        {
                            Id = 72,
                            Code = "Ibri-511",
                            Name = "Ibri"
                        },
                        new
                        {
                            Id = 73,
                            Code = "Al-Buraimi -512",
                            Name = "Al-Buraimi "
                        },
                        new
                        {
                            Id = 74,
                            Code = "Yanqul-513",
                            Name = "Yanqul"
                        },
                        new
                        {
                            Id = 75,
                            Code = "Dhank-514",
                            Name = "Dhank"
                        },
                        new
                        {
                            Id = 76,
                            Code = "Al-Araqi -515",
                            Name = "Al-Araqi "
                        },
                        new
                        {
                            Id = 77,
                            Code = "Al-Akhdar -Ibri 516",
                            Name = "Al-Akhdar -Ibri 516"
                        },
                        new
                        {
                            Id = 78,
                            Code = "Al-Sinainah -517",
                            Name = "Al-Sinainah "
                        },
                        new
                        {
                            Id = 79,
                            Code = "Mahda-518",
                            Name = "Mahda"
                        },
                        new
                        {
                            Id = 80,
                            Code = "Khasab-811",
                            Name = "Khasab"
                        },
                        new
                        {
                            Id = 81,
                            Code = "Bakha-812",
                            Name = "Bakha"
                        },
                        new
                        {
                            Id = 82,
                            Code = "Daba-813",
                            Name = "Daba"
                        },
                        new
                        {
                            Id = 83,
                            Code = "Madha-814",
                            Name = "Madha"
                        },
                        new
                        {
                            Id = 84,
                            Code = "Nizwa-611",
                            Name = "Nizwa"
                        },
                        new
                        {
                            Id = 85,
                            Code = "Bahla-612",
                            Name = "Bahla"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeclarationAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNo")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Registration.Domain.Entities.RelationshipMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Father"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Mother"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "GrandFather"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "GrandMother"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherTongue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PassportExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VisaExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisaNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Address", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Registration", "Registration")
                        .WithOne("Address")
                        .HasForeignKey("Registration.Domain.Entities.Address", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Registration.Domain.Entities.ApplicationDetail", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Registration", "Registration")
                        .WithOne("ApplicationDetail")
                        .HasForeignKey("Registration.Domain.Entities.ApplicationDetail", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Registration.Domain.Entities.GradeSchoolMaster", b =>
                {
                    b.HasOne("Registration.Domain.Entities.GradeMaster", "Grade")
                        .WithMany("GradeSchools")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Parent", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Registration", "Registration")
                        .WithOne("Parent")
                        .HasForeignKey("Registration.Domain.Entities.Parent", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Student", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Registration", "Registration")
                        .WithOne("Student")
                        .HasForeignKey("Registration.Domain.Entities.Student", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Registration.Domain.Entities.GradeMaster", b =>
                {
                    b.Navigation("GradeSchools");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Registration", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("ApplicationDetail");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
